<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.62.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\hcep.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HCEP.Core\HCEP.Core.csproj" />
  </ItemGroup>
</Project>
