<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <RootNamespace>HCEP.Kinect.Bridge</RootNamespace>
    <AssemblyName>HCEP.Kinect.Bridge</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup Condition="Exists('$(KINECTSDK10_DIR)')">
    <Reference Include="Microsoft.Kinect">
      <HintPath>$(KINECTSDK10_DIR)\Assemblies\Microsoft.Kinect.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
